### ISSUE TITLE
Send pin number in gree_ir.

### ISSUE THREAD

**Issue by te0203** [Hagakurje/ESPHome_Gree_AC#10]
Good afternoon. I am using your code. It works, but there is a question. Let's say the air conditioner is not one, but several, and that for each you need to write a separate file gree_ir.h with your own number Gpio? How to pass the pin number to this file, for example, a global variable. 

```
# in ir_bedroom.yaml
substitutions:
    transmitter_pin: "14"

globals:
- id: transmitter_pin
  type: uint16_t
  restore_value: no
  initial_value: $transmitter_pin

# in gree_ir.h
const uint16_t kIrLed = id(transmitter_pin);
```

Something like this, but it doesn't work for me. Help me please. Thank you.
